config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'todo_apps/main#index'

  scope module: 'todo_apps' do
    resources :main, only: [:index]
    resources :user_sessions, only: [:create, :destroy]
    resources :users, except: [:index] do
      resources :todos
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :todos, dependent: :destroy
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations: false)

  attr_accessor :updating_password

  # associations
  has_many :todos, dependent: :destroy
  has_many :categories, through: :todos

  # callbacks
  before_save :email_downcase

  # validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  validate :password_validity, if: :should_validate_password?

  private

  def email_downcase
    self.email = self.email.downcase
  end

  def should_validate_password?
    updating_password || new_record?
  end

  def updating_password!
    self.updating_password = true
  end

  def password_validity
    self.errors.add(:password, :blank) if self.password.blank?
    validates_length_of :password, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED
    validates_confirmation_of :password, allow_blank: false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_apps/base_controller.rb
class TodoApps::BaseController < ApplicationController
  layout "todo_app"

  before_action :authenticate!
  before_action :current_user

  private

  def authenticate!
    unless current_user
      redirect_to main_index_path
      flash[:alert] = "You need to login before performing this action"
    end
  end

  def current_user
    @user = User.find_by(id: session[:user_id])
  end

  def user_login(user)
    session[:user_id] = user.id
  end

  def user_logout()
    session.delete(:user_id)
  end

  def redirect_if_already_login
    if current_user
      flash[:success] = "You Already Login"
      redirect_to user_path(current_user)
    end
  end

end

app/controllers/todo_apps/main_controller.rb
class TodoApps::MainController < TodoApps::BaseController

  skip_before_action :authenticate!
  skip_before_action :current_user
  before_action :redirect_if_already_login
  before_action :already_registered, only: [:create]

  def index
    @user = User.new()
  end

end

app/controllers/todo_apps/todos_controller.rb
class TodoApps::TodosController < TodoApps::BaseController

  before_action :current_todo, except: [:new, :create]
  before_action :categories, only: [:new, :edit]

  def new
    @todo = current_user.todos.new()
  end

  def create
    if current_user.todos.create(todo_params)
      flash[:success] = "todo success"
      redirect_to user_path(@user)
    else
      flash[:success] = "todo failed"
      redirect_to :back
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      flash[:success] = "update todo success"
      redirect_to user_path(@user)
    else
      flash[:success] = "update todo failed"
      redirect_to :back
    end
  end

  def destroy
    @todo.destroy
    flash[:success] = "Todo Deleted"
    redirect_to :back
  end


  private

  def todo_params
    params.require(:todo).permit(:title, :description, :category_id, :status, :user_id)
  end

  def current_todo
    @todo = Todo.find(params[:id])
  end

  def categories
    @categories = Category.all
  end

end

app/controllers/todo_apps/user_sessions_controller.rb
class TodoApps::UserSessionsController < TodoApps::BaseController

  skip_before_action :authenticate!
  skip_before_action :current_user
  before_action :redirect_if_already_login, except: [:destroy]

  def create
    user = User.find_by(email: user_params[:email])
    if user && user.authenticate(user_params[:password])
      flash[:success] = "Login Success"
      user_login(user)
      redirect_to user_path(user)
    else
      flash[:alert] = "Login Failed"
      redirect_to :back
    end
  end

  def destroy
    user_logout()
    redirect_to main_index_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/controllers/todo_apps/users_controller.rb
class TodoApps::UsersController < TodoApps::BaseController

  skip_before_action :authenticate!, only: [:create]
  skip_before_action :current_user, only: [:create]
  before_action :already_registered, only: [:create]

  def create
    if user = User.create(user_params)
      flash[:success] = "Register Success"
      user_login(user)
      redirect_to user_path(user)
    else
      flash[:alert] = "Register Failed"
      redirect_to :back
    end
  end

  def show
    @todos = @user.todos
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User Update Success"
    else
      flash[:alert] = "User Update Failed"
    end
    redirect_to :back
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def already_registered
    user = User.find_by(email: user_params[:email])
    if user.present?
      flash[:alert] = "You Already Have An Account With Us"
      redirect_to :back
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }
    [flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/todo_app.slim
doctype html
html
  head
    title
      | TodoApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'todo_apps/shared/menu'
    = render 'todo_apps/shared/flash'
    #wrapper
      .container
        = yield
    = render 'todo_apps/shared/footer'
    = render 'todo_apps/shared/signup_modal'

app/views/todo_apps/main/index.slim
.main-div
  h1.center
    | Welcome To Your Todo Apps
  p
    |  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea vero non nesciunt dolor corporis voluptatem fugiat quibusdam sed autem. Optio distinctio ipsum alias commodi adipisci minima animi numquam earum. Deserunt.
    | &nbsp;
    |  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea vero non nesciunt dolor corporis voluptatem fugiat quibusdam sed autem. Optio distinctio ipsum alias commodi adipisci minima animi numquam earum. Deserunt.
    | &nbsp;
    |  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea vero non nesciunt dolor corporis voluptatem fugiat quibusdam sed autem. Optio distinctio ipsum alias commodi adipisci minima animi numquam earum. Deserunt.
  p
    |  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea vero non nesciunt dolor corporis voluptatem fugiat quibusdam sed autem. Optio distinctio ipsum alias commodi adipisci minima animi numquam earum. Deserunt.
    | &nbsp;
    |  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea vero non nesciunt dolor corporis voluptatem fugiat quibusdam sed autem. Optio distinctio ipsum alias commodi adipisci minima animi numquam earum. Deserunt.
    | &nbsp;
    |  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea vero non nesciunt dolor corporis voluptatem fugiat quibusdam sed autem. Optio distinctio ipsum alias commodi adipisci minima animi numquam earum. Deserunt.

app/views/todo_apps/shared/_flash.slim
#flash
  .center
    = flash_messages

app/views/todo_apps/shared/_footer.slim
#footer
  .footer-text
    span
      | © Todo Apps. All rights reserved.

  .footer-links
    i.fa.fa-pied-piper

app/views/todo_apps/shared/_menu.slim
#menu
  .menu-logo
    h3
      | Hello

  - if current_page?(root_path) || current_page?(main_index_path)
    .menu-list
      ul
        li
          a.btn.btn-link.btn-lg.menu-button[type="button" data-toggle="modal" data-target="#signUpModal"]
            | Sign Up
        li
          a.btn.btn-link.btn-lg.menu-button[type="button" data-toggle="modal" data-target="#signInModal"]
            | Login
  - else
    .menu-list
      ul
        li
          = form_for @user, url: user_session_path(@user), :method => "delete" do |f|
            = f.submit "Logout", class: 'btn btn-link menu-button'

app/views/todo_apps/shared/_signup_modal.slim
.container
  / signupmodal
  #signUpModal.modal.fade[role="dialog"]
    .modal-dialog
      .modal-content
        .modal-header
          button.close[type="button" data-dismiss="modal"]
            | ×
          h4.modal-title
            | User SignUp
        .modal-body
          .form-user
            = form_for @user, url: users_path do |f|
              .row
                .col-md-offset-4.col-md-4
                  = f.label :first_name
                  = f.text_field :first_name, class: 'form-control', required: 'required'
              .row
                .col-md-offset-4.col-md-4
                  = f.label :last_name
                  = f.text_field :last_name, class: 'form-control', required: 'required'
              .row
                .col-md-offset-4.col-md-4
                  = f.label :email
                  = f.text_field :email, class: 'form-control', required: 'required'
              .row
                .col-md-offset-4.col-md-4
                  = f.label :password
                  = f.password_field :password, class: 'form-control', required: 'required'
              .row
                .col-md-offset-4.col-md-4
                  = f.label :password_confirmation
                  = f.password_field :password_confirmation, class: 'form-control', required: 'required'
              .row
                .col-md-offset-4.col-md-4
                  br/
                  = f.submit "Register", class: 'btn btn-info btn-block'
        .modal-footer
          button.btn.btn-default[type="button" data-dismiss="modal"]
            | Close


  / signInModal
  #signInModal.modal.fade[role="dialog"]
    .modal-dialog
      .modal-content
        .modal-header
          button.close[type="button" data-dismiss="modal"]
            | ×
          h4.modal-title
            | User SignUp
        .modal-body
          .form-user
            = form_for @user, url: user_sessions_path do |f|
              .row
                .col-md-offset-4.col-md-4
                  = f.label :email
                  = f.text_field :email, class: 'form-control', required: 'required'
              .row
                .col-md-offset-4.col-md-4
                  = f.label :password
                  = f.password_field :password, class: 'form-control', required: 'required'
              .row
                .col-md-offset-4.col-md-4
                  br/
                  = f.submit "SignIn", class: 'btn btn-info btn-block'
        .modal-footer
          button.btn.btn-default[type="button" data-dismiss="modal"]
            | Close

app/views/todo_apps/todos/_todo_field.slim
.row
  .col-md-offset-4.col-md-4
    = f.label :title
    = f.text_field :title, class: 'form-control', required: 'required'
.row
  .col-md-offset-4.col-md-4
    = f.label :description
    = f.text_field :description, class: 'form-control', required: 'required'
.row
  .col-md-offset-4.col-md-4
    = f.label :category_id
    = f.select :category_id, @categories.collect { |cat| [cat.name, cat.id]}, class: 'form-control', required: 'required'

app/views/todo_apps/todos/edit.slim
.page.center
  h3
    | Edit Todo

.form-todo
  = form_for @todo, url: user_todo_path(@user, @todo) do |f|
    = render 'todo_apps/todos/todo_field', f: f
    .row
      .col-md-offset-4.col-md-4
        br/
        = f.submit "Update", class: 'btn btn-info btn-block'

app/views/todo_apps/todos/new.slim
.page.center
  h3
    | New Todo

.form-todo
  = form_for @todo, url: user_todos_path(@user) do |f|
    = render 'todo_apps/todos/todo_field', f: f
    .row
      .col-md-offset-4.col-md-4
        br/
        = f.submit "Create", class: 'btn btn-info btn-block'

app/views/todo_apps/user_sessions/new.slim
h3
  | User Sessions

.form-user
  = form_for @user, url: user_sessions_path do |f|
    .row
      .col-md-offset-4.col-md-4
        = f.label :first_name
        = f.text_field :first_name, class: 'form-control', required: 'required'
    .row
      .col-md-offset-4.col-md-4
        = f.label :last_name
        = f.text_field :last_name, class: 'form-control', required: 'required'
    .row
      .col-md-offset-4.col-md-4
        = f.label :email
        = f.text_field :email, class: 'form-control', required: 'required'
    .row
      .col-md-offset-4.col-md-4
        = f.label :password
        = f.password_field :password, class: 'form-control', required: 'required'
    .row
      .col-md-offset-4.col-md-4
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'form-control', required: 'required'
    .row
      .col-md-offset-4.col-md-4
        br/
        = f.submit "Register", class: 'btn btn-info btn-block'

app/views/todo_apps/users/_user_field.slim
.form-user
  = form_for @user, url: user_path(@user) do |f|
    .row
      .col-md-4
        = f.label :first_name
        = f.text_field :first_name, class: 'form-control', required: 'required'
      .col-md-4
        = f.label :last_name
        = f.text_field :last_name, class: 'form-control', required: 'required'
      .col-md-4
        = f.label :email
        = f.text_field :email, class: 'form-control', required: 'required'
    .row
      .col-md-12
        br/
        = f.submit "Update", class: 'btn btn-info btn-block'

app/views/todo_apps/users/show.slim
.page.center
  h3
    | Show

  h4
    | Hello #{@user.first_name}

h5
  | User Info

  = render 'todo_apps/users/user_field'
h5
  = link_to 'Create New Todo', new_user_todo_path(@user)
h5
  | Todo Lists

table.table.table-striped
  tr
    th
      | Title
    th
      | Description
    th
      | Category Id
    th
      | Status
    th
      | Created At
    th
      | Action

  - @todos.each do |todo|
    tr
      td
        = todo.title
      td
        = todo.description
      td
        = todo.category.name
      td
        = todo.status
      td
        = todo.created_at
      td
        = link_to "Edit", edit_user_todo_path(@user, todo)
        | &nbsp;
        = link_to "Delete", user_todo_path(@user, todo), method: 'delete'